[jump_box]
jump-box ansible_host=20.62.119.46 \
         ansible_user=azureuser \
         ansible_ssh_private_key_file=~/.ssh/id_rsa

[elk]
elk-vm ansible_host=10.0.1.5 \
       ansible_user=azureuser \
       ansible_ssh_private_key_file=~/.ssh/id_rsa \
       ansible_ssh_common_args='-o ProxyJump=jump-box'

[webservers]
dvwa-vm ansible_host=10.0.1.6 \
        ansible_user=azureuser \
        ansible_ssh_private_key_file=~/.ssh/id_rsa \
        ansible_ssh_common_args='-o ProxyJump=jump-box'

[kali]
kali-vm ansible_host=10.0.1.7 \
        ansible_user=azureuser \
        ansible_ssh_private_key_file=~/.ssh/id_rsa \
        ansible_ssh_common_args='-o ProxyJump=jump-box'
